services:
  app:
    build:
      context: ./docker/php
    container_name: saas_app
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - saas_network

  nginx:
    image: nginx:alpine
    container_name: saas_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - saas_network

  mysql:
    image: mysql:8.0
    container_name: saas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saas_db
      MYSQL_USER: saas_user
      MYSQL_PASSWORD: saas_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - saas_network

  phpmyadmin:                         
    image: phpmyadmin:latest
    container_name: saas_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - saas_network

  mailpit:
    image: axllent/mailpit:edge
    container_name: saas_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - saas_network

  queue-worker:
    build:
      context: ./docker/php
    container_name: saas_queue_worker
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    depends_on:
      - app
      - mysql
    networks:
      - saas_network

volumes:
  mysql_data:

networks:
  saas_network:

